/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Vistas;

import AccesoADatos.IngredientesData;
import Entidades.Ingredientes;
import java.awt.Dimension;
import java.util.ArrayList;
import javax.swing.JComponent;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author charl
 */
public class IngredientesVista extends javax.swing.JInternalFrame {

    private JComponent Barra = ((javax.swing.plaf.basic.BasicInternalFrameUI) getUI()).getNorthPane();
    private Dimension DimensionBarra = null;
    private DefaultTableModel modelo=new DefaultTableModel();
    public IngredientesVista() {
        initComponents();
        ((javax.swing.plaf.basic.BasicInternalFrameUI) this.getUI()).setNorthPane(null);
        cargarCabecera();
        cargarCombo();
        limpiarTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        Tabla = new javax.swing.JTable();
        Nuevo = new javax.swing.JLabel();
        Editar = new javax.swing.JLabel();
        Eliminar = new javax.swing.JLabel();
        Listar = new javax.swing.JLabel();
        Nombre = new javax.swing.JLabel();
        Calorias = new javax.swing.JLabel();
        TextoNombre = new javax.swing.JTextField();
        TextoCalorias = new javax.swing.JTextField();
        Aceptar = new javax.swing.JLabel();
        Cancelar = new javax.swing.JLabel();
        ComboBox = new javax.swing.JComboBox<>();
        Fondo = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(Tabla);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 357, 710, 200));

        Nuevo.setFont(new java.awt.Font("Roboto Black", 0, 24)); // NOI18N
        Nuevo.setForeground(new java.awt.Color(153, 255, 255));
        Nuevo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Nuevo.setText("NUEVO");
        Nuevo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(Nuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 100, 90, 40));

        Editar.setFont(new java.awt.Font("Roboto Black", 0, 24)); // NOI18N
        Editar.setForeground(new java.awt.Color(153, 255, 255));
        Editar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Editar.setText("EDITAR");
        Editar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(Editar, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 100, -1, 40));

        Eliminar.setBackground(new java.awt.Color(204, 204, 255));
        Eliminar.setFont(new java.awt.Font("Roboto Black", 0, 24)); // NOI18N
        Eliminar.setForeground(new java.awt.Color(153, 255, 255));
        Eliminar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Eliminar.setText("ELIMINAR");
        Eliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(Eliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 100, -1, 40));

        Listar.setFont(new java.awt.Font("Roboto Black", 0, 24)); // NOI18N
        Listar.setForeground(new java.awt.Color(153, 255, 255));
        Listar.setText("LISTAR");
        Listar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(Listar, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 100, -1, 40));

        Nombre.setFont(new java.awt.Font("Roboto Black", 0, 24)); // NOI18N
        Nombre.setForeground(new java.awt.Color(255, 255, 255));
        Nombre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Nombre.setText("Nombre");
        getContentPane().add(Nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 160, -1, -1));

        Calorias.setBackground(new java.awt.Color(204, 204, 204));
        Calorias.setFont(new java.awt.Font("Roboto Black", 0, 24)); // NOI18N
        Calorias.setForeground(new java.awt.Color(255, 255, 255));
        Calorias.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Calorias.setText("Calorias");
        getContentPane().add(Calorias, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 200, -1, -1));
        getContentPane().add(TextoNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 160, 200, -1));
        getContentPane().add(TextoCalorias, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 200, 200, -1));

        Aceptar.setFont(new java.awt.Font("Roboto Black", 0, 22)); // NOI18N
        Aceptar.setForeground(new java.awt.Color(204, 255, 255));
        Aceptar.setText("ACEPTAR");
        getContentPane().add(Aceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 270, -1, -1));

        Cancelar.setFont(new java.awt.Font("Roboto Black", 0, 22)); // NOI18N
        Cancelar.setForeground(new java.awt.Color(204, 255, 255));
        Cancelar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Cancelar.setText("CANCELAR");
        getContentPane().add(Cancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 270, -1, -1));

        getContentPane().add(ComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 150, 110, -1));

        Fondo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/FAC.png"))); // NOI18N
        getContentPane().add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, 560));

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Aceptar;
    private javax.swing.JLabel Calorias;
    private javax.swing.JLabel Cancelar;
    private javax.swing.JComboBox<String> ComboBox;
    private javax.swing.JLabel Editar;
    private javax.swing.JLabel Eliminar;
    private javax.swing.JLabel Fondo;
    private javax.swing.JLabel Listar;
    private javax.swing.JLabel Nombre;
    private javax.swing.JLabel Nuevo;
    private javax.swing.JTable Tabla;
    private javax.swing.JTextField TextoCalorias;
    private javax.swing.JTextField TextoNombre;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
private void cargarCabecera() {
modelo.addColumn("ID");
modelo.addColumn("Nombre");
modelo.addColumn("Categoria");
modelo.addColumn("Calorias");
modelo.addColumn("Estado");
Tabla.setModel(modelo);
    }
private void cargarCombo(){
    ComboBox.addItem("Categoria");
    ComboBox.addItem("Vegetales");
    ComboBox.addItem("Tuberculos");
    ComboBox.addItem("Lacteos");
    ComboBox.addItem("Carnes");
    ComboBox.addItem("Legumbres");
    ComboBox.addItem("Bebida");
}
private void cargarTabla(String x){
     IngredientesData ingreData=new IngredientesData();
     ArrayList<Ingredientes>ingredientes =new ArrayList<>();
     ingredientes =ingreData.listarIngredientesPorCateg(x);
     for (Ingredientes ingre : ingredientes) {
        modelo.addRow(new Object[]{ingre.getIdIngredientes(),ingre.getNombre(),ingre.getCategoria(),ingre.getCantCalorias(),ingre.isEstado()});
    }
    
}
private void limpiarTabla(){
    int filas=modelo.getRowCount();
    for (int i = filas-1; i > -1; i--) {
        modelo.removeRow(i);
    }
}
}
