package Vistas;


import java.awt.Color;
import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author charl
 */
public class VPrueba4 extends javax.swing.JFrame {

    private PacienteVista br=new PacienteVista();
    int xMouse, yMouse;
    
    public VPrueba4() {
        initComponents();
        this.setLocationRelativeTo(null);
       PanelInicio.setVisible(false);
       PanelBuscar.setVisible(false);
       
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ImageIcon icon = new ImageIcon(getClass().getResource("/imagenes/fondo3.png"));
        Image image = icon.getImage();
        escritorio = new javax.swing.JDesktopPane(){
            public void paintComponent(Graphics g){
                g.drawImage(image,0,0,getWidth(),getHeight(),this);

            }
        };
        BSuperior = new javax.swing.JPanel();
        PanelCerrar = new javax.swing.JPanel();
        LabelCerrar = new javax.swing.JLabel();
        Blateral = new javax.swing.JPanel();
        Home = new javax.swing.JLabel();
        Buscar = new javax.swing.JLabel();
        Editar = new javax.swing.JLabel();
        Paciente = new javax.swing.JLabel();
        PanelInicio = new javax.swing.JPanel();
        LabelInicio = new javax.swing.JLabel();
        PanelBuscar = new javax.swing.JPanel();
        LabelBuscar = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        BSuperior.setBackground(new java.awt.Color(255, 255, 255));
        BSuperior.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                BSuperiorMouseDragged(evt);
            }
        });
        BSuperior.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BSuperiorMouseEntered(evt);
            }
        });

        PanelCerrar.setBackground(new java.awt.Color(255, 255, 255));
        PanelCerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                PanelCerrarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                PanelCerrarMouseExited(evt);
            }
        });
        PanelCerrar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LabelCerrar.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        LabelCerrar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelCerrar.setText("X");
        LabelCerrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LabelCerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LabelCerrarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                LabelCerrarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                LabelCerrarMouseExited(evt);
            }
        });
        PanelCerrar.add(LabelCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(3, 0, 40, 30));

        javax.swing.GroupLayout BSuperiorLayout = new javax.swing.GroupLayout(BSuperior);
        BSuperior.setLayout(BSuperiorLayout);
        BSuperiorLayout.setHorizontalGroup(
            BSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BSuperiorLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(PanelCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        BSuperiorLayout.setVerticalGroup(
            BSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelCerrar, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
        );

        Blateral.setBackground(new java.awt.Color(255, 255, 255));
        Blateral.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Home.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Home.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/casa2.png"))); // NOI18N
        Home.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HomeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                HomeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                HomeMouseExited(evt);
            }
        });
        Blateral.add(Home, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, 30));

        Buscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/buscar2.png"))); // NOI18N
        Buscar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Buscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BuscarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BuscarMouseExited(evt);
            }
        });
        Blateral.add(Buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 30, 30));

        Editar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/nuevo2.png"))); // NOI18N
        Editar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Blateral.add(Editar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, -1, -1));

        Paciente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/paciente2.png"))); // NOI18N
        Paciente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Paciente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PacienteMouseClicked(evt);
            }
        });
        Blateral.add(Paciente, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, -1, 30));

        PanelInicio.setBackground(new java.awt.Color(204, 204, 204));
        PanelInicio.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LabelInicio.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        LabelInicio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelInicio.setText("INICIO");
        PanelInicio.add(LabelInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 140, 30));

        PanelBuscar.setBackground(new java.awt.Color(204, 204, 204));
        PanelBuscar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LabelBuscar.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        LabelBuscar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelBuscar.setText("BUSCAR");
        PanelBuscar.add(LabelBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 140, 30));

        escritorio.setLayer(BSuperior, javax.swing.JLayeredPane.DEFAULT_LAYER);
        escritorio.setLayer(Blateral, javax.swing.JLayeredPane.DEFAULT_LAYER);
        escritorio.setLayer(PanelInicio, javax.swing.JLayeredPane.DEFAULT_LAYER);
        escritorio.setLayer(PanelBuscar, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(escritorioLayout.createSequentialGroup()
                .addComponent(Blateral, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(PanelInicio, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE)
                    .addComponent(PanelBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(105, 599, Short.MAX_VALUE))
            .addComponent(BSuperior, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(escritorioLayout.createSequentialGroup()
                .addComponent(BSuperior, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(PanelInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(PanelBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(Blateral, javax.swing.GroupLayout.PREFERRED_SIZE, 599, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void HomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HomeMouseClicked
      
        br.dispose();
    }//GEN-LAST:event_HomeMouseClicked

    private void PacienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PacienteMouseClicked
        barras();
    }//GEN-LAST:event_PacienteMouseClicked

    private void HomeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HomeMouseEntered
        PanelInicio.setVisible(true);
    }//GEN-LAST:event_HomeMouseEntered

    private void BuscarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BuscarMouseEntered
        PanelBuscar.setVisible(true);
    }//GEN-LAST:event_BuscarMouseEntered

    private void HomeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HomeMouseExited
        PanelInicio.setVisible(false);
    }//GEN-LAST:event_HomeMouseExited

    private void BuscarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BuscarMouseExited
        PanelBuscar.setVisible(false);
    }//GEN-LAST:event_BuscarMouseExited

    private void PanelCerrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelCerrarMouseEntered
        PanelCerrar.setBackground(Color.red);
        LabelCerrar.setForeground(Color.white);
    }//GEN-LAST:event_PanelCerrarMouseEntered

    private void PanelCerrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelCerrarMouseExited
        PanelCerrar.setBackground(Color.white);
        LabelCerrar.setForeground(Color.black);
    }//GEN-LAST:event_PanelCerrarMouseExited

    private void BSuperiorMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BSuperiorMouseDragged
        int x=evt.getXOnScreen();
        int y=evt.getYOnScreen();
        this.setLocation(x-xMouse, y-yMouse);
    }//GEN-LAST:event_BSuperiorMouseDragged

    private void BSuperiorMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BSuperiorMouseEntered
        xMouse=evt.getX();
        yMouse=evt.getY();
    }//GEN-LAST:event_BSuperiorMouseEntered

    private void LabelCerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LabelCerrarMouseClicked
        System.exit(0);
    }//GEN-LAST:event_LabelCerrarMouseClicked

    private void LabelCerrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LabelCerrarMouseEntered
       PanelCerrar.setBackground(Color.red);
        LabelCerrar.setForeground(Color.white);
    }//GEN-LAST:event_LabelCerrarMouseEntered

    private void LabelCerrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LabelCerrarMouseExited
        PanelCerrar.setBackground(Color.white);
        LabelCerrar.setForeground(Color.black);
    }//GEN-LAST:event_LabelCerrarMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VPrueba4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VPrueba4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VPrueba4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VPrueba4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VPrueba4().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BSuperior;
    private javax.swing.JPanel Blateral;
    private javax.swing.JLabel Buscar;
    private javax.swing.JLabel Editar;
    private javax.swing.JLabel Home;
    private javax.swing.JLabel LabelBuscar;
    private javax.swing.JLabel LabelCerrar;
    private javax.swing.JLabel LabelInicio;
    private javax.swing.JLabel Paciente;
    private javax.swing.JPanel PanelBuscar;
    private javax.swing.JPanel PanelCerrar;
    private javax.swing.JPanel PanelInicio;
    private javax.swing.JDesktopPane escritorio;
    // End of variables declaration//GEN-END:variables
public void barras(){
        br.setVisible(true);
        escritorio.add(br);
        escritorio.moveToFront(br);
        br.setLocation(52, 36);
}
}
