package Vistas;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.Image;
import java.beans.PropertyVetoException;
import javax.swing.ImageIcon;
import javax.swing.JInternalFrame;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author charl
 */
public class VPrueba4 extends javax.swing.JFrame {
    
    private PacienteVista paciente = new PacienteVista();
    private ArmarDieta dieta = new ArmarDieta();
    private ArmarComida comida = new ArmarComida();
    private IngredientesVista ingredientes = new IngredientesVista();
    int xMouse, yMouse;
    
    public VPrueba4() {
        initComponents();
        this.setLocationRelativeTo(null);
        PanelInicio.setVisible(false);
        PanelPaciente.setVisible(false);
        PanelComida.setVisible(false);
        PanelDieta.setVisible(false);
        PanelIngredientes.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ImageIcon icon = new ImageIcon(getClass().getResource("/imagenes/FondoPrincipal.png"));
        Image image = icon.getImage();
        escritorio = new javax.swing.JDesktopPane(){
            public void paintComponent(Graphics g){
                g.drawImage(image,0,0,getWidth(),getHeight(),this);

            }
        };
        BSuperior = new javax.swing.JPanel();
        PanelCerrar = new javax.swing.JPanel();
        LabelCerrar = new javax.swing.JLabel();
        Blateral = new javax.swing.JPanel();
        LHome = new javax.swing.JLabel();
        LDieta = new javax.swing.JLabel();
        LPaciente = new javax.swing.JLabel();
        LComida = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        PanelInicio = new javax.swing.JPanel();
        LabelInicio = new javax.swing.JLabel();
        PanelPaciente = new javax.swing.JPanel();
        LabelBuscar = new javax.swing.JLabel();
        PanelDieta = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        PanelComida = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        PanelIngredientes = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        escritorio.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        escritorio.setPreferredSize(new java.awt.Dimension(800, 600));

        BSuperior.setBackground(new java.awt.Color(255, 255, 255));
        BSuperior.setPreferredSize(new java.awt.Dimension(800, 35));
        BSuperior.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                BSuperiorMouseDragged(evt);
            }
        });
        BSuperior.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BSuperiorMouseEntered(evt);
            }
        });

        PanelCerrar.setBackground(new java.awt.Color(255, 255, 255));
        PanelCerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                PanelCerrarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                PanelCerrarMouseExited(evt);
            }
        });
        PanelCerrar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LabelCerrar.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        LabelCerrar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelCerrar.setText("X");
        LabelCerrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LabelCerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LabelCerrarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                LabelCerrarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                LabelCerrarMouseExited(evt);
            }
        });
        PanelCerrar.add(LabelCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(3, 0, 40, 30));

        javax.swing.GroupLayout BSuperiorLayout = new javax.swing.GroupLayout(BSuperior);
        BSuperior.setLayout(BSuperiorLayout);
        BSuperiorLayout.setHorizontalGroup(
            BSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BSuperiorLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(PanelCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        BSuperiorLayout.setVerticalGroup(
            BSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelCerrar, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
        );

        Blateral.setBackground(new java.awt.Color(255, 255, 255));
        Blateral.setPreferredSize(new java.awt.Dimension(50, 600));
        Blateral.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LHome.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/casa2.png"))); // NOI18N
        LHome.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LHomeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                LHomeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                LHomeMouseExited(evt);
            }
        });
        Blateral.add(LHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, 30));

        LDieta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/nuevo2.png"))); // NOI18N
        LDieta.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LDieta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LDietaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                LDietaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                LDietaMouseExited(evt);
            }
        });
        Blateral.add(LDieta, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, -1, -1));

        LPaciente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/paciente2.png"))); // NOI18N
        LPaciente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LPaciente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LPacienteMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                LPacienteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                LPacienteMouseExited(evt);
            }
        });
        Blateral.add(LPaciente, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, -1, 30));

        LComida.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LComida.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cubiertosFinal.png"))); // NOI18N
        LComida.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LComida.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LComidaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                LComidaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                LComidaMouseExited(evt);
            }
        });
        Blateral.add(LComida, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, -1, -1));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/manzanaFinal.png"))); // NOI18N
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel1MouseExited(evt);
            }
        });
        Blateral.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, -1, -1));

        PanelInicio.setBackground(new java.awt.Color(204, 204, 204));
        PanelInicio.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LabelInicio.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        LabelInicio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelInicio.setText("INICIO");
        PanelInicio.add(LabelInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 140, 30));

        PanelPaciente.setBackground(new java.awt.Color(204, 204, 204));
        PanelPaciente.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LabelBuscar.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        LabelBuscar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelBuscar.setText("PACIENTE");
        PanelPaciente.add(LabelBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 120, 30));

        PanelDieta.setBackground(new java.awt.Color(204, 204, 204));
        PanelDieta.setPreferredSize(new java.awt.Dimension(140, 30));
        PanelDieta.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("DIETA");
        PanelDieta.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 120, 30));

        PanelComida.setBackground(new java.awt.Color(204, 204, 204));
        PanelComida.setMinimumSize(new java.awt.Dimension(140, 30));
        PanelComida.setPreferredSize(new java.awt.Dimension(140, 30));
        PanelComida.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("COMIDA");
        PanelComida.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(3, 0, 110, 30));

        PanelIngredientes.setBackground(new java.awt.Color(204, 204, 204));
        PanelIngredientes.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("INGREDIENTES");
        PanelIngredientes.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 140, 30));

        escritorio.setLayer(BSuperior, javax.swing.JLayeredPane.DEFAULT_LAYER);
        escritorio.setLayer(Blateral, javax.swing.JLayeredPane.DEFAULT_LAYER);
        escritorio.setLayer(PanelInicio, javax.swing.JLayeredPane.DEFAULT_LAYER);
        escritorio.setLayer(PanelPaciente, javax.swing.JLayeredPane.DEFAULT_LAYER);
        escritorio.setLayer(PanelDieta, javax.swing.JLayeredPane.DEFAULT_LAYER);
        escritorio.setLayer(PanelComida, javax.swing.JLayeredPane.DEFAULT_LAYER);
        escritorio.setLayer(PanelIngredientes, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BSuperior, javax.swing.GroupLayout.DEFAULT_SIZE, 798, Short.MAX_VALUE)
            .addGroup(escritorioLayout.createSequentialGroup()
                .addComponent(Blateral, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(PanelInicio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PanelDieta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PanelComida, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PanelPaciente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PanelIngredientes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 602, Short.MAX_VALUE))
        );
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(escritorioLayout.createSequentialGroup()
                .addComponent(Blateral, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(escritorioLayout.createSequentialGroup()
                .addComponent(BSuperior, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67)
                .addComponent(PanelInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67)
                .addComponent(PanelPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addComponent(PanelDieta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(74, 74, 74)
                .addComponent(PanelComida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(76, 76, 76)
                .addComponent(PanelIngredientes, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LPacienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LPacienteMouseClicked
        if (dieta.isVisible() == true) {
            cerrarVentana(dieta);
            abrirVentanas(paciente);
        } else if (comida.isVisible() == true) {
            cerrarVentana(comida);
            abrirVentanas(paciente);
        } else if (ingredientes.isVisible() == true) {
            cerrarVentana(ingredientes);
            abrirVentanas(paciente);
        } else if(paciente.isVisible()==true){
            cerrarVentana(paciente);
            abrirVentanas(paciente);
        }else{
            abrirVentanas(paciente);
        }
        
    }//GEN-LAST:event_LPacienteMouseClicked

    private void LHomeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LHomeMouseExited
        PanelInicio.setVisible(false);
    }//GEN-LAST:event_LHomeMouseExited

    private void LHomeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LHomeMouseEntered
        PanelInicio.setVisible(true);
    }//GEN-LAST:event_LHomeMouseEntered

    private void LHomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LHomeMouseClicked
        if (paciente.isVisible() == true) {
            cerrarVentana(paciente);
        } else if (dieta.isVisible() == true) {
            cerrarVentana(dieta);
        } else if (comida.isVisible() == true) {
            cerrarVentana(comida);
        }else if(ingredientes.isVisible()==true){
            cerrarVentana(ingredientes);
        }

    }//GEN-LAST:event_LHomeMouseClicked

    private void BSuperiorMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BSuperiorMouseEntered
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_BSuperiorMouseEntered

    private void BSuperiorMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BSuperiorMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_BSuperiorMouseDragged

    private void PanelCerrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelCerrarMouseExited
        PanelCerrar.setBackground(Color.white);
        LabelCerrar.setForeground(Color.black);
    }//GEN-LAST:event_PanelCerrarMouseExited

    private void PanelCerrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelCerrarMouseEntered
        PanelCerrar.setBackground(Color.red);
        LabelCerrar.setForeground(Color.white);
    }//GEN-LAST:event_PanelCerrarMouseEntered

    private void LabelCerrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LabelCerrarMouseExited
        PanelCerrar.setBackground(Color.white);
        LabelCerrar.setForeground(Color.black);
    }//GEN-LAST:event_LabelCerrarMouseExited

    private void LabelCerrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LabelCerrarMouseEntered
        PanelCerrar.setBackground(Color.red);
        LabelCerrar.setForeground(Color.white);
    }//GEN-LAST:event_LabelCerrarMouseEntered

    private void LabelCerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LabelCerrarMouseClicked
        System.exit(0);
    }//GEN-LAST:event_LabelCerrarMouseClicked

    private void LPacienteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LPacienteMouseEntered
        PanelPaciente.setVisible(true);
    }//GEN-LAST:event_LPacienteMouseEntered

    private void LPacienteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LPacienteMouseExited
        PanelPaciente.setVisible(false);
    }//GEN-LAST:event_LPacienteMouseExited

    private void LDietaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LDietaMouseEntered
        PanelDieta.setVisible(true);
    }//GEN-LAST:event_LDietaMouseEntered

    private void LDietaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LDietaMouseExited
        PanelDieta.setVisible(false);
    }//GEN-LAST:event_LDietaMouseExited

    private void LComidaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LComidaMouseEntered
        PanelComida.setVisible(true);
    }//GEN-LAST:event_LComidaMouseEntered

    private void LComidaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LComidaMouseExited
        PanelComida.setVisible(false);
    }//GEN-LAST:event_LComidaMouseExited

    private void LDietaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LDietaMouseClicked
        if (paciente.isVisible() == true) {
            cerrarVentana(paciente);
            abrirVentanas(dieta);
        } else if (comida.isVisible() == true) {
            cerrarVentana(comida);
            abrirVentanas(dieta);
        } else if (ingredientes.isVisible() == true) {
            cerrarVentana(ingredientes);
            abrirVentanas(dieta);
        } else if(dieta.isVisible()==true){
            cerrarVentana(dieta);
            abrirVentanas(dieta);
        }else{
            abrirVentanas(dieta);
        }
        
    }//GEN-LAST:event_LDietaMouseClicked

    private void LComidaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LComidaMouseClicked
        if (paciente.isVisible() == true) {
            cerrarVentana(paciente);
            abrirVentanas(comida);
        } else if (dieta.isVisible() == true) {
            cerrarVentana(dieta);
            abrirVentanas(comida);
        } else if (ingredientes.isVisible() == true) {
            cerrarVentana(ingredientes);
            abrirVentanas(comida);
        } else if(comida.isVisible()==true){
            cerrarVentana(comida);
            abrirVentanas(comida);
        }else{
            abrirVentanas(comida);
        }
        
    }//GEN-LAST:event_LComidaMouseClicked

    private void jLabel1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseEntered
        PanelIngredientes.setVisible(true);
    }//GEN-LAST:event_jLabel1MouseEntered

    private void jLabel1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseExited
        PanelIngredientes.setVisible(false);
    }//GEN-LAST:event_jLabel1MouseExited

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        if (paciente.isVisible() == true) {
            cerrarVentana(paciente);
            abrirVentanas(ingredientes);
        } else if (dieta.isVisible() == true) {
            cerrarVentana(dieta);
            abrirVentanas(ingredientes);
        } else if (comida.isVisible() == true) {
            cerrarVentana(comida);
            abrirVentanas(ingredientes);
        } else if(ingredientes.isVisible()==true){
            cerrarVentana(ingredientes);
            abrirVentanas(ingredientes);
        }else{
            abrirVentanas(ingredientes);
        }
    }//GEN-LAST:event_jLabel1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VPrueba4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VPrueba4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VPrueba4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VPrueba4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VPrueba4().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BSuperior;
    private javax.swing.JPanel Blateral;
    private javax.swing.JLabel LComida;
    private javax.swing.JLabel LDieta;
    private javax.swing.JLabel LHome;
    private javax.swing.JLabel LPaciente;
    private javax.swing.JLabel LabelBuscar;
    private javax.swing.JLabel LabelCerrar;
    private javax.swing.JLabel LabelInicio;
    private javax.swing.JPanel PanelCerrar;
    private javax.swing.JPanel PanelComida;
    private javax.swing.JPanel PanelDieta;
    private javax.swing.JPanel PanelIngredientes;
    private javax.swing.JPanel PanelInicio;
    private javax.swing.JPanel PanelPaciente;
    private javax.swing.JDesktopPane escritorio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables

    private void abrirVentanas(JInternalFrame x) {
        x.setVisible(true);
        escritorio.add(x);
        escritorio.moveToFront(x);
        x.setLocation(50, 35);
    }
    
    private void cerrarVentana(JInternalFrame x) {
        x.dispose();
        escritorio.remove(x);
    }
}
